# -*- coding: utf-8 -*-
"""Byte_Pair_Encoding_from_scratch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i9sVpZnwY2M52T793J8xahXZ9_FZIKM4

# Byte Pair Encoding
It was originally created as a data compression algorithm.
Later it was repurposed for subword tokenization which is a very useful method for handing rare words and to manage Out of Vocabulary (OOV) words.

Before jumping on the code, you must read about the Byte Pair Encodin in order to get an idea about it.

Steps involved in BPE:


*   Spilt the words in corpus into characters after appending end word token '</w>'
*   Initialize the vocabulary with unique characters in the corpus
*   Compute the frequency of a pair of characters or character sequences in corpus
*   Merge the most frequent pair in corpus
*   Save the best pair to the vocabulary
*   Repeat 3rd to 5th steps for a certain number of iterations

First read these articles:
* https://www.analyticsvidhya.com/blog/2020/05/what-is-tokenization-nlp/
* https://towardsdatascience.com/byte-pair-encoding-the-dark-horse-of-modern-nlp-eb36c7df4f10 (Well curated article on BPE)
* https://iq.opengenus.org/byte-pair-encoding/ (Must read for better visualization)
*  https://web.stanford.edu/class/cs224n/slides/cs224n-2019-lecture12-subwords.pdf (Page no: 18-24_ --> Byte Pair Encoding)
* http://ethen8181.github.io/machine-learning/deep_learning/subword/bpe.html
"""

# import necessary libraries
import re
import string
from collections import Counter, defaultdict
import nltk
from nltk.corpus import stopwords
from nltk import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
from tqdm import tqdm_notebook
from textblob import TextBlob
from textblob import Word

# Text corpus
corpus = '''Tropical rainforests are tropical, moist forests of semi-deciduous varieties distributed across nine West African countries. Institute for Sea Research conducted a temperature record dating back to 700,000 years ago.[2] Several conservation and development demographic settings are such that the most loss of rain forests has occurred in countries of higher population growth. Lack of dependable data and survey information in some countries has made the account of areas of unbroken forest and/or under land use change and their relation to economic indicators difficult to ascertain. Hence, the amount and rate of deforestation in Africa are less known than other regions of tropics.
The term deforestation refers to the complete obstruction of forest canopy cover for means of agriculture, plantations, cattle-ranching, and other non-forest fields. Other forest use changes for example are forest disintegration (changing the spatial continuity and creating a mosaic of forest blocks and other land cover types), and dreadful conditions (selective logging of woody species for profitable purposes that affects the forest subfloor and the biodiversity).[2] The general meaning to the term deforestation is linked not only to the value system but the type of measurement designed to assess it. Thus, the same interpretations of deforestation cause noticeable changes in the estimate of forests cleared.
One reason for forest depletion is to grow cash crops. Nine West African countries depend on cash crop exports. Products like gum, copal, rubber, cola nuts, and palm oil provide rather steady income revenue for the West African countries. Land use change spoils entire habitats with the forests. Converting forests into timber is another cause of deforestation. Over decades, the primary forest product was commercial timber. Urbanized countries account for a great percentage of the world's wood consumption, that increased greatly between 1950 and 1980. Simultaneously, preservation measures were reinforced to protect European and American forests.[2] Economic growth and growing environmental protection in industrialized European countries made request for tropical hardwood become strong in West Africa. In the first half of the 1980s, an annual forest loss of 7,200 km2 (2,800 sq mi) was note down along the Gulf of Guinea, a figure equivalent to 4-5 per cent of the total remaining rain forest area.[2] By 1985, 72% of West Africa's rainforests had been transformed into fallow lands and an additional 9% had been opened up by timber exploitation.[2]
Tropical timber became a viable choice to European wood following World War II, as trade with East European countries stop and timber noticeably became sparse in western and southern Europe. Despite efforts to promote lesser known timber species use, the market continued to focus on part of the usable timber obtainable. West Africa was prone to selective harvesting practices; while conservationists blamed the timber industry and the farmers for felling trees, others believe rain forest destruction is connected to the problem of fuel wood.[2] The contribution of fuel wood consumption to tree stock decline in Africa is believed to be significant. It is generally believed that firewood provides 75% of the energy used in sub-Sahara Africa.[2] With the high demand, the consumption of wood for fuel exceeds the renewal of forest cover.
African Pygmies living in the Dzanga-Sangha Special Reserve
The rain forests which remain in West Africa now merely are how they were hardly 30 years ago. In Guinea, Liberia and the Ivory Coast, there is almost no primary forest cover left unscathed; in Ghana the situation is much worse, and nearly all the rain forest are cut down. Guinea-Bissau loses 200 to 350 km2 (77 to 135 sq mi) of forest yearly, Senegal 500 km2 (190 sq mi) of wooded savanna, and Nigeria 6,000,050,000 of both. Liberia exploits 800 km2 (310 sq mi) of forests each year. Extrapolating from present rates of loss, botanist Peter Raven pictures that the majority of the world's moderate and smaller rain forests (such as in Africa) could be ruined in forty years. Tropical Africa is about 18% of the world total covering 20 million km2 (7.7 million sq mi) of land in West and Central Africa.[2] The region has been facing deforestation in various degrees of intensity throughout the recent decades. The actual rate of deforestation varies from one country to another and accurate data does not exist yet. Recent estimates show that the annual pace of deforestation in the region can vary from 150 km2 (58 sq mi) in Gabon to 2,900 km2 (1,100 sq mi) in Cote d'Ivoire. Remaining tropical forest still cover major areas in Central Africa but are abridged by patches in West Africa.
The African Timber Organization member countries (ATO) eventually recognized the cooperation between rural people and their forest environment. Customary law gives residents the right to use trees for firewood, fell trees for construction, and collect of forest products and rights for hunting or fishing and grazing or clearing of forests for maintenance agriculture. Other areas are called "protected forests", which means that uncontrolled clearings and unauthorized logging are forbidden. After World War II, commercial exploitation increased until no West African forestry department was able of making the law. By comparison with rain forests in other places of the world in 1973, Africa showed the greatest infringement though in total volume means, African timber production accounted just one third compared to that of Asia.[2] The difference was due to the variety of trees in Africa forests and the demand for specific wood types in Europe.
Forestry regulations in east Africa were first applied by colonial governments, but they were not strict enough to fill forest exploitation. It wasn't until the 1970s that the inadequate performance of forest regulations was recognized. The Tropical Forestry Action Plan was conceived in 1987 by the World Resources Institute in cooperation with the Food and Agriculture Organization, the United Nations Development Program (UNDP) and the World Bank with hopes of halting tropical forest destruction.[2] In its bid to stress forest conservation and development, the World Bank provided $111,103 million in building countries, especially in Africa, to help in developing long range forest conservation and management programs meant for ending deforestation.'''

corpus

"""## Text preprocessing"""

# lower the sentences
corpus = "".join([word.lower() for word in corpus if word not in string.punctuation])
# remove all digits from the text
pattern = r'[0-9]'
corpus = "".join([re.sub(pattern, '', word) for word in corpus])
corpus = "".join(corpus.split('\n'))
# remove stopwords
stop_words = set(stopwords.words('english'))
corpus = ' '.join([word for word in corpus.split() if word not in stop_words])
corpus

# word tokens
tokens = word_tokenize(corpus)
corpus = corpus.split()
print(tokens)
print(corpus)
if(tokens == corpus):
  print('True')

# Lemmatization
wordnet_lemmatizer = WordNetLemmatizer() 
corpus = [wordnet_lemmatizer.lemmatize(word) for word in corpus]

print(corpus)

corpus = " ".join(corpus)
print(corpus)

"""## Step 1: Build vocab from text corpus"""

def build_vocab(corpus: str) -> dict:
  # Separate each character in every word in the corpus by a space and add mark end os token
  tokens = [" ".join(word) + " </w>" for word in corpus.split()]
  # Count frequency of tokens in corpus
  vocab = Counter(tokens)
  return vocab

build_vocab(corpus).items()

"""## Get counts of pairs of consecutive sequences"""

def get_stats(vocab: dict) ->  str:
  pairs = defaultdict(int)
  for word, frequency in vocab.items():
    symbols = word.split()
    # Counting up frequencies of pairs
    for i in range(len(symbols)-1):
      pairs[symbols[i], symbols[i+1]] += frequency
  return pairs

"""## Step 3: Merge all occurences of the most frequent pair"""

def merge_vocab(pair: tuple, v_in: dict) -> dict:
  v_out = {}

  # re.escape
  # ensures the characters of our input pair will be handled as it is and
  # not get mistreated as special characters in the regular expression.
  bigram = re.escape(' '.join(pair))
  p = re.compile(r'(?<!\S)' + bigram + r'(?!\S)')
  for word in v_in:
    w_out = p.sub(''.join(pair), word)   # For eg: 'a b' gets replaced by 'ab' in 'a b b c a d a b'
    v_out[w_out] = v_in[word]
  return v_out

"""## Run all the functions"""

# step 1
vocab = build_vocab(corpus)
# hyperparameter 
# number of iterations of merges we want in our vocabulary
num_merges = 300
# Step 2
for i in range(num_merges):
  pairs = get_stats(vocab)
  if not pairs:
    break
  # Step 3
  best = max(pairs, key=pairs.get)
  vocab = merge_vocab(best, vocab)

# Final vacabulary
print(vocab)

"""Here, ends the Byte Pair Encoding algorithm!
I hope you understood the main concepts behind the algorithm.
"""





